config/routes.rb
Rails.application.routes.draw do
  with_period = /[^\/]+/
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # general
  get "timeline", to: "general#timeline", as: "timeline"

  ##############
  # MULTIMEDIA #
  ##############
  get "multimedia", to: "items#multimedia", as: "multimedia"
  ### audio
  get "multimedia/audio", to: "items#multimedia_audio", as: "audio"
  get "multimedia/audio/:id", to: "items#multimedia_audio_item", as: "audio_item"
  ### images
  get "multimedia/images", to: "items#multimedia_images", as: "images"
  # note: topic has same path as ID so need constraint on matches
  get "multimedia/images/:topic", to: "items#multimedia_images", as: "image_topic",
    topic: /(aerial|field|group|parade|people)/
  get "multimedia/images/:id", to: "items#multimedia_image",
    as: "image", id: with_period
  ### footage
  get "multimedia/footage", to: "items#multimedia_footage", as: "footage"
  get "multimedia/footage/:id", to: "items#multimedia_footage_clip",
    as: "footage_clip", id: with_period

  #############
  # DOCUMENTS #
  #############
  get "documents", to: "documents#home", as: "documents"

  scope "/documents/drill" do
    Orchid::Routing.draw(section: "drill",
      routes: ["home", "browse", "browse_facet", "item", "search"],
      scope: "/documents/drill"
    )
  end

  scope "/documents/correspondence" do
    Orchid::Routing.draw(section: "correspondence",
      routes: ["home", "browse", "browse_facet", "item", "search"],
      scope: "/documents/correspondence"
    )
  end

  scope "/documents/newspapers" do
    Orchid::Routing.draw(section: "newspapers",
      routes: ["home", "browse", "browse_facet", "item", "search"],
      scope: "/documents/newspapers"
    )
  end

  # stories
  get "stories", to: "stories#index", as: "stories"
  get "stories/accounts", to: "stories#accounts", as: "accounts"
  get "stories/accounts/:id", to: "stories#account", as: "account"
  get "stories/features", to: "stories#features", as: "features"
  get "stories/features/:id", to: "stories#feature", as: "feature"

  #########
  # ABOUT #
  #########

  get "about/acknowledgements", to: "general#about_thanks", as: "about_thanks"
  get "about/archives", to: "general#about_archives", as: "about_archives"
  get "about/history", to: "general#about_history", as: "about_history"
  get "about/technology", to: "general#about_tech", as: "about_tech"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/documents_controller.rb
class DocumentsController < ItemsController
end

app/controllers/items_override.rb
ItemsController.class_eval do

  def multimedia_footage
    options = params.permit!.deep_dup
    options["f"] = [] if options["f"].blank?
    options["f"] << "category2|Footage"

    @facets = $api.query({
      "facet" => "keywords",
      "facet_sort" => "term|asc",
      "num" => 0,
      "f" => ["category2|Footage"]
    })

    @res = $api.query(options)
    @route_path = "footage_path"
    # essentially using search_preset but with my own view
  end

  def multimedia_footage_clip
    item_retrieve(params["id"])
  end

  def multimedia_image
    @res = $api.get_item_by_id(params["id"]).first
  end

  def multimedia_images
    options = params.permit!.deep_dup
    options["f"] = [] if options["f"].blank?
    options["f"] << "category2|Images"
    if params["topic"].present?
      options["f"] << "topics|#{params["topic"]}"
      @title = "#{params["topic"].titleize} Images"
    else
      @title = "Images"
    end

    @facets = $api.query({
      "facet" => "topics",
      "facet_sort" => "term|asc",
      "num" => 0,
      "f" => ["category2|Images"]
    })
    @res = $api.query(options)
    @route_path = "images_path"
    render_overridable "items", "search_preset"
  end

end

app/controllers/multimedia_controller.rb
class MultimediaController < ApplicationController

  def footage
    options = params.permit!.deep_dup
    options["f"] = [] if options["f"].blank?
    options["f"] << "subcategory|Footage"

    @facets = $api.query({
      "facet" => "keywords",
      "facet_sort" => "term|asc",
      "num" => 0,
      "f" => ["subcategory|Footage"]
    })

    @res = $api.query(options)
    @route_path = "footage_path"
    # essentially using search_preset but with my own view
  end

  def footage_clip
    item_retrieve(params["id"])
  end

  def image
    @res = $api.get_item_by_id(params["id"]).first
  end

  def images
    @title = "Images"

    options = params.permit!.deep_dup
    options["f"] = [] if options["f"].blank?
    options["f"] << "subcategory|Images"
    if params["topic"].present?
      options["f"] << "topics|#{params["topic"]}"
    end

    @facets = $api.query({
      "facet" => "topics",
      "facet_sort" => "term|asc",
      "num" => 0,
      "f" => ["subcategory|Images"]
    })
    @res = $api.query(options)
    @route_path = "images_path"
    render_overridable "items", "search_preset"
  end

  private

  # copied directly from items_controller.rb
  # modified only to use $api instead of section specific
  # and to use footage title
  def item_retrieve(id)
    @res = $api.get_item_by_id(id).first
    if @res
      url = @res["uri_html"]
      @html = Net::HTTP.get(URI.parse(url)) if url
      @title = @res["title"]

      render_overridable("items", "show")
    else
      @title = t "item.no_item", id: id,
        default: "No item with identifier #{id} found!"
      render_overridable("items", "show_not_found", status: 404)
    end
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Orchid::ApplicationHelper

  def about_nav_class(nav_item)
    if params["action"] == nav_item
      "btn btn-filter btn-primary"
    else
      "btn btn-filter btn-warning"
    end
  end

  # need facet_selected? for footage page
  # and it's otherwise only available to items controller
  def facet_selected?(type, facet="")
    if params["f"].present?
      if facet && facet.length > 0
        params["f"].include?("#{type}|#{facet}")
      else
        params["f"].any? { |f| f.include?(type) }
      end
    else
      false
    end
  end

  def topic_selected?(facet)
    params["topic"] == facet
  end

end

app/helpers/display_helper.rb
module DisplayHelper
  include Orchid::DisplayHelper
end

app/helpers/facet_helper.rb
module FacetHelper
  include Orchid::FacetHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  include Orchid::ItemsHelper


  # because of how the link is being structured, this method needs to return only
  # the path and NOT an entire link, differing from the orchid expected behavior
  def search_item_link(item)
    category2 = item["category2"].downcase

    if category2 == "audio"
      id = item["identifier"].split(".").last
      path = audio_item_path(id: id)

    elsif category2 == "correspondence & papers"
      path = correspondence_item_path(id: item["identifier"])

    elsif category2 == "drill"
      path = drill_item_path(id: item["identifier"])

    elsif category2 == "features"
      id = item["identifier"].split(".").last
      path = feature_path(id: id)

    elsif category2 == "footage"
      path = footage_clip_path(id: item["identifier"])

    elsif category2 == "images"
      path = image_path(id: item["identifier"])

    elsif category2 == "newspaper"
      path = newspapers_item_path(id: item["identifier"])

    elsif category2 == "personal accounts"
      id = item["identifier"].split(".").last
      path = account_path(id: id)

    else
      path = item_path(id: item["identifier"])
    end

    path
  end

  def title_label(item)
    # would need to modify this if creating a multilingual site
    untitled = t("search.results.item.no_title", default: "Untitled")
    item["title"].present? ? item["title"] : untitled
  end

end

app/helpers/pagination_helper.rb
module PaginationHelper
  include Orchid::PaginationHelper
end

app/helpers/sort_helper.rb
module SortHelper
  include Orchid::SortHelper
end

app/views/correspondence/general/index.html.erb
<% @title = "Correspondence & Papers" %>

<h1>Correspondence & Papers</h1>

<div class="row">
  <div class="col-md-9">
    <p class="lead">
      There is a wealth of information about the band in the Archives in the form of correspondence, student records, bills, and more. These documents can be found in Chancellor records, Board of Regents minutes, military records, and collections left behind by individual past band directors.
    </p>
    <p>
      The vast majority of the records in Archives have not yet been digitized, but several documents are available on the website at this time.
    </p>
  </div>
  <div class="col-md-3">
    <%= image_tag "correspondence.jpg", alt: "First page of letter from Professor of Military and Tactics" %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">

    <h2 class="text-center">Search</h2>

    <%= form_tag prefix_path(route_path), method: "get",
      class: "input-group" do %>
      <!-- search box -->
      <%= text_field_tag(:q, params[:q], :placeholder => t("search.placeholder", default: "Search for..."), :class => "form-control") %>
      <!-- add existing search parameters to query -->
      <%= render_overridable("items", "hidden_fields") %>
      <!-- submit -->
      <span class="input-group-btn">
        <%= submit_tag t("search.submit", default: "Search"), class: "btn btn-primary", name: nil, data: { disable_with: false } %>
      </span>
    <% end %>
    <%= render_overridable("items", "help") %>
  </div>
  <div class="col-md-6">
    <h2 class="text-center">Browse</h2>
    <div class="filter-buttons">
      <%= link_to "Browse All Papers", correspondence_search_path, class: "btn btn-primary btn-filter", role: "button" %>
    </div>
  </div>
</div>

app/views/correspondence/items/_search_res_items.html.erb
<%# OVERRIDE FROM ORCHID %>

<% if @res.count > 0 %>
  <div class="flex_row buffer-bottom-sm">
    <% @res.items.each do |item| %>
      <%= link_to search_item_link(item), class: "searchResults flex_col-md" do %>
        <div class="search_results_image">
          <% if item["cover_image"] %>
            <%= image_tag iiif(item["cover_image"]) %>
          <% elsif item["category2"] == "Newspaper" %>
            <%= image_tag "no_image_newspaper.jpg", size: "150" %>
          <% else %>
            <%= image_tag "no_image.png", size: "150" %>
          <% end %>
        </div>
        <div class="search_results_info">
          <span class="link_style"><%= title_label(item) %></span>
          <div class="search_item_info">
            <ul class="search_item_metadata">
              <% if item["date_display"].present? %>
                <li>
                  <%= metadata(item, t("search.results.item.date",
                    default: "Date"), "date_display", link: false) %>
                </li>
              <% end %>
              <%# creator can be a multivalued or single keyword field %>
              <% if item["creator"].present? %>
                <li>
                  <%= metadata(item, t("search.results.item.creator",
                    default: "Creator"), "creator.name", link: false) %>
                </li>
              <% end %>
              <%# removing format, rights, publisher, and source, since at least for now these are the same for each item %>
            </ul>
            <% if item["highlight"].present? %>
              <div class="search_results_text">
                <% item["highlight"].each do |key, hls| %>
                  <div class="search_results_highlights">
    
                    <% hls.each do |hl| %>
                      <p><%= hl.html_safe %></p>
                    <% end %>
                  </div>
                <% end %>
              </div><%# /search_results_text %>
            <% end %> <%# /item["highlight"].present? %>
          </div> <%# /search_item_info %>
        </div><%# /search_results_info %>
      <%end%><%# /a searchResults %>
    <% end %><%# /res.items.each %>
  </div><%# /flex_row %>
<% end %><%# /if %>

app/views/documents/home.html.erb
<% @title = "Documents" %>

<p class="lead">The band left in its wake an impressive paper trail, spanning newspaper accounts, correspondence, scrapbooks, and manuals. Although the bulk of these have yet to be digitized, they are available for visitors to view in the University Archives & Special Collections.</p>

<p>In this section of the website, you will find an index of hundreds of articles from student newspapers, such as <em>The Hesperian Student</em> and <em>The Daily Nebraskan</em>, which mention the band. Additionally, drill charts and memorandums have been scanned and transcribed under Drill and Correspondence and Papers. Be sure to check out the <%= link_to "1937 Band Manual", drill_item_path(id: "band.doc.0002") %>, which is a fascinating look into how the band used to function pre-WWII.</p>

<div class="section-nav-container">
  <%= link_to :newspapers_home, class: "section-nav section-nav-documents section-nav-documents-newspapers" do %>
    <div class="section-nav-title">Newspapers</div>
    <div class="section-nav-subtitle">Browse an index of student newspaper articles</div>
    <div class="section-nav-image"></div>
  <% end %>

  <%= link_to :correspondence_home, class: "section-nav section-nav-documents
    section-nav-documents-correspondence" do %>
    <div class="section-nav-title">Correspondence and Papers</div>
    <div class="section-nav-subtitle">Letters, petitions, and more</div>
    <div class="section-nav-image"></div>
  <% end %>

  <%= link_to :drill_home, class: "section-nav section-nav-documents" do %>
    <div class="section-nav-title">Drill</div>
    <div class="section-nav-subtitle">Band manuals and drill charts</div>
    <div class="section-nav-image"></div>
  <% end %>
</div>

app/views/drill/general/index.html.erb
<% @title = "Drill" %>

<h1>Drill</h1>

<div class="row">
  <div class="col-md-8">
    <p class="lead">
      What is a marching band without drill? Early in the band's history, precision military drill was dictated by officer orders and signals from the drum major, but over time as drill became more complicated it was communicated to band members through written instructions and diagrams.
    </p>
    <p>
      The <%= link_to "1937 Band Manual", drill_item_path(id: "band.doc.0002") %> is an excellent resource for those interested in pre-WWII band discipline, charts, and music.
    </p>
  </div>
  <div class="col-md-4">
    <%= image_tag "drill.jpg", alt: "Page from 1937 band manual with instructions to spell HUSKERS" %>
    <p>1937 Band Manual</p>
  </div>
</div>

<div class="row">
  <div class="col-md-6">

    <h2 class="text-center">Search</h2>

    <%= form_tag prefix_path(route_path), method: "get",
      class: "input-group" do %>
      <!-- search box -->
      <%= text_field_tag(:q, params[:q], :placeholder => t("search.placeholder", default: "Search for..."), :class => "form-control") %>
      <!-- add existing search parameters to query -->
      <%= render_overridable("items", "hidden_fields") %>
      <!-- submit -->
      <span class="input-group-btn">
        <%= submit_tag t("search.submit", default: "Search"), class: "btn btn-primary", name: nil, data: { disable_with: false } %>
      </span>
    <% end %>
    <%= render_overridable("items", "help") %>
  </div>
  <div class="col-md-6">
    <h2 class="text-center">Browse</h2>
    <div class="filter-buttons">
      <%= link_to "Browse All Drill Documents", drill_search_path, class: "btn btn-primary btn-filter", role: "button" %>
    </div>
  </div>
</div>

app/views/general/timeline/_1876.html.erb
<div class="timeline-article">
  <div class="meta-date">
    <span class="date">1876</span>
  </div>
  <%= render layout: "general/timeline/element", locals: {
    direction: direction,
    title: "Military Department Formed",
    id: "military-dept",
    image: "332100-00003.jpg",
    image_attr: nil,
    image_caption: "ROTC cadets on parade ground, 1881.",
    image_link: "332100-00003" } do %>
    <p>The Morrill Act, through which the University of Nebraska was created, stipulated that land grant institutions must support "...at least one college where the leading object shall be, without excluding other scientific and classical studies, and including military tactics, to teach such branches of learning as are related to agriculture and the mechanic arts...". In 1876, to fulfill the Act’s requirement for military tactics to be taught, the fledgling University established the Military Science program.</p>

    <div class="resources">
      Sources and Further Reading
      <ul>
        <li><a target="_blank" rel="nofollow noopener" href="https://catalog.archives.gov/id/299817">Read the Morrill Act online</a> through the National Archives</li>
        <li><a target="_blank" rel="nofollow noopener" href="https://www.loc.gov/rr/program/bib/ourdocs/morrill.html">Library of Congress resources</a> related to the Morrill Act</li>
        <li><a target="_blank" rel="nofollow noopener" href="https://www.unl.edu/armyrotc/cadre-1">Big Red Battalion ROTC History</a></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/general/timeline/_1918.html.erb
<div class="timeline-article">
  <div class="meta-date">
    <span class="date">1918</span>
  </div>
  <%= render layout: "general/timeline/element", locals: {
    direction: direction,
    title: "'Billy' Quick Becomes Band Director",
    id: "quick",
    image: "570904-00058.jpg",
    image_attr: nil,
    image_caption: "1925 group portrait. Original caption:<br/>
      'University of Nebraska Band, Wm. T. Quick director'",
    image_link: "570904-00058" } do %>
    <p>In 1918, sweeping changes to the military department were taking place due to the Great War. The Student Army Training Corps (SATC) was formed, temporarily replacing the Reserve Officer Training Corps (ROTC), which had only just replaced the Cadets a few years before.  In the midst of this, William T. Quick, affectionately known as "Billy", took over direction of the band.  Quick would remain the band's director until 1937, the longest stretch of time in the band's history up until that point. During his tenure, the band grew in size and popularity while continuing to be part of the military.</p>

    <p>A century later, Quick's reputation for kindness remains a pillar of his legacy.  His successor, Donald Lentz, said of Quick "He was just the finest person you had ever met."  An entire page of <em>Pride of the Cornhuskers</em> is filled with band members fondly reminiscing about Quick. Loved by his music students and band members, Quick returned the sentiment upon his retirement, remarking to <em>The Daily Nebraskan</em> about the band: "...I love the work no matter how they play. I'll direct them until I die."</p>

    <div class="resources">
      Sources and Further Reading
      <ul>
        <li>
          <a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1918-09-30/ed-1/seq-1/">Forty-Five Band Men Selected In Tryouts,"</a> <em>The Daily Nebraskan</em>, September 30, 1918.
        </li>
        <li>
          <a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1937-05-20/ed-1/seq-1/">"'Billy' Quick Reminisces on 19 Happy Years as Band Director,"</a> <em>The Daily Nebraskan</em>, May 20, 1937.
        </li>

        <li>Steffens, Gary R. "Billy," <em>Pride of the Cornhuskers, 1981. Taylor Publishing Company, Dallax, TX. p 60.</em></li>

        <li><a target="_blank" rel="nofollow noopener" href=" https://www.unl.edu/armyrotc/cadre-1">ROTC History at UNL</a></li>

        <li>Lentz shares memories of Quick in an <%= link_to "interview with George Round", "/stories/lentz-interview" %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/general/timeline/_1927.html.erb
<div class="timeline-article">
  <div class="meta-date">
    <span class="date">1927</span>
  </div>
  <%= render layout: "general/timeline/element", locals: {
    direction: direction,
    title: "Sousa Visits and Composes March for University",
    id: "sousa",
    image: "band.img.0025.jpg",
    image_attr: "Photo Credit: Jessica Dussault",
    image_caption: "The Sousa trophy on display",
    image_link: "band.img.0025" } do %>
    
    <p>November 1st, 1927, "The March King" John Philip Sousa and his band paid a visit to Lincoln, Nebraska for two much anticipated concerts on the newly updated Coliseum stage. His visit became a large event for the city of Lincoln. Over a dozen high school bands came to town for "band day" and paraded through the streets. The lucky bands took part  in both concerts, "formed into one huge organization and directed by Sousa himself." <em>The Daily Nebraskan</em> reported that even the University of Kansas band planned to take part in the proceedings, playing Sousa marches during the concert intermissions. An estimated 5,000 people attended the two concerts to hear Sousa's band and the other participants in "band day."</p>

    <p>The legacy of Sousa's visit still endures today. During his visit, Sousa presented the R.O.T.C. band with a silver "loving cup" trophy for the regiment's rating the previous year, a trophy which rests today in the School of Music's halls. Also, at the request of Chancellor Burnett, Sousa composed the "University of Nebraska March" the following year.</p>


    <div class="resources">
      Sources and Further Reading
      <ul>
        <li><%= link_to "Listen to a recording", "/stories/marches.html" %> of the Symphonic Band performing "The University of Nebraska" march</li>

        <li>Read more about the "University of Nebraska March" in an article written for the 150th anniversary of the university: <a target="_blank" rel="nofollow noopener" href="https://news.unl.edu/newsrooms/today/article/n150-sousa-pens-special-march-for-nebraska-u/">"Sousa Pens Special March for Nebraska U"</a></li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-10-16/ed-1/seq-1/">"Stage is Made Ready for Band,"</a> <em>The Daily Nebraskan</em>, October 16, 1927.</li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-10-19/ed-1/seq-1/">"The Man Who Won the War,"</a> <em>The Daily Nebraskan</em>, October 19, 1927.</li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-09-29/ed-1/seq-1/">"Date Set for Sousa Event,"</a> <em>The Daily Nebraskan</em>, September 29, 1927.</li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-10-09/ed-1/seq-1/">"Sousa Says Newspapers Furnish Best Sources of Inspiration,"</a> <em>The Daily Nebraskan</em>, October 9, 1927.</li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-10-23/ed-1/seq-1/">"Sousa Will Hear Band Day Program,"</a> <em>The Daily Nebraskan</em>, October 23, 1927.</li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-10-23/ed-1/seq-3/">"Kansas Band Plays Here,"</a> <em>The Daily Nebraskan</em>, October 23, 1927.</li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-10-30/ed-1/seq-1/">"Fifteen Bands Visit Lincoln,"</a> <em>The Daily Nebraskan</em>, October 30, 1927.</li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-11-01/ed-1/seq-1/">"Sousa's Band Plays Today in Two Concerts,"</a> <em>The Daily Nebraskan</em>, November 1, 1927.</li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-11-02/ed-1/seq-1/">"Sousa Pleases Large Number with Program,"</a> <em>The Daily Nebraskan</em>, November 2, 1927.</li>

        <li><a target="_blank" rel="nofollow noopener" href="https://nebnewspapers.unl.edu/lccn/sn96080312/1927-11-03/ed-1/seq-1/">"Leader Will Compose March for Nebraska,"</a> <em>The Daily Nebraskan</em>, November 3, 1927.</li>
      </ul>
    </div>
  <% end %>
</div>

app/views/general/timeline/_1943.html.erb
<div class="timeline-article">
  <div class="meta-date">
    <span class="date">1943</span>
  </div>
  <%= render layout: "general/timeline/element", locals: {
    direction: direction,
    title: "Women Fill the Ranks During WWII",
    id: "womenWar",
    image: "570904-00069.jpg",
    image_attr: nil,
    image_caption: "Martha Nickerson Omaha, French Horn.
      <br/>She wears the standard inside uniform. 1944.",
    image_link: "570904-00069" } do %>
    <p>World War II brought with it many changes for the University of Nebraska as well as the band program. The 1944 yearbook explained that "...the armed forces drew heavily upon the personnel of the...band. This year for the first time in its history, coeds were permitted to march with the band…" Band director Prof. Lentz recalled that "during those war years we had to rely on the ladies all the way through." Women continued to be involved in marching band until 1946, when women were excluded from marching, but continued to play in concert band.</p>

    <div class="resources">
      Sources and Further Reading
      <ul>
        <li><%= link_to "Interview with Donald Lentz", "stories/lentz-interview" %></li>

        <li><a target="_blank" rel="nofollow noopener" href="http://yearbooks.unl.edu/yearbook.php?year=1944,328#page/148/mode/transcription">"R.O.T.C. Band."</a> <em>The Cornhusker</em>, 1944, p 142.</li>

        <li><a target="_blank" rel="nofollow noopener" href="http://yearbooks.unl.edu/yearbook.php?year=1947,504#page/224/mode/transcription">"Varsity Band,"</a> <em>The Cornhusker</em>, 1947, p 220.</li>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/body/_header.html.erb
<%# overridden in order to place the nav over the header image %>

<div id="header" role="banner">
  <div class="container banner-header">
    <%= render_overridable("layouts/body", "title") %>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <%= render_overridable("layouts/body", "languages") %>
      <%= render_overridable("layouts/body", "navbar") %>
      <%= render_overridable("layouts/body", "breadcrumbs") %>
    </nav>
  </div>
</div>

app/views/layouts/body/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <ul class="nav navbar-nav mr-auto">
      <li class="<%= active?(/^#{config.relative_url_root}\/multimedia/,request.path) %> nav-item">
        <%= link_to "Sights & Sounds", :multimedia, class: "nav-link" %>
      </li>
      <li class="<%= active?(/^#{config.relative_url_root}\/documents/,request.path) %> nav-item">
        <%= link_to "Documents", :documents,
          class: "nav-link" %>
      </li>
      <li class="<%= active?(timeline_path) %> nav-item">
        <%= link_to "Timeline", :timeline, class: "nav-link" %>
      </li>
      <li class="<%= active?(/^#{config.relative_url_root}\/stories/,request.path) %> nav-item">
        <%= link_to "Stories", :stories, class: "nav-link" %>
      </li>
      <!-- Removing browse temporarily until we figure out what we want -->
      <!--
      <li class="<%# active?(/^#{config.relative_url_root}\/browse/,
        request.path) %> nav-item">
        <%# link_to t("browse.title", default: "Browse"), :browse, class: "nav-link" %>
      </li>
      -->
      <li class="<%= active?(search_path) %> nav-item">
        <%= link_to t("search.title", default: "Search"), :search, rel: "search", class: "nav-link" %>
      </li>
      <li class="<%= active?(about_path) %> nav-item">
        <%= link_to t("about.title", default: "About"), :about, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div><!-- /navbar --> 

app/views/layouts/body/_title.html.erb
<%# TODO only thing overridden was to add navbar-brand, but if that not needed erase this partial %>

<div class="container site-title-container">
  <%= link_to home_path do %>
    <div class="h1">
      <% if I18n.exists?("general.project_name", locale) %>
        <span class="site-title navbar-brand"><%= t "general.project_name" %></span>
      <% end %>
      <% if I18n.exists?("general.project_subtitle", locale) %>
        <small class="site-subtitle"><%= t "general.project_subtitle" %></small>
      <% end %>
    </div>
  <% end %>
</div>

app/views/multimedia/audio_item.html.erb
<%= render "multimedia/audio/#{params[:id]}" %>

app/views/stories/account.html.erb
<% @ext_css = add_assets(@ext_css, ["stories"] ) %>

<%= render "stories/accounts/#{params[:id]}" %>

app/views/stories/feature.html.erb
<% @ext_css = add_assets(@ext_css, ["stories"] ) %>

<%= render "stories/features/#{params[:id]}" %>